name: Rest Dev Branch to Master at 1am each day
on:
  schedule:
    - cron: "36 * * * *"
jobs:
  reset:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: Reset dev branch to master
        uses: nicksnell/action-reset-repo@master
        with:
          reset_branch: dev